-- gespeichert: erg_prognose
-- v_prognose, gespeichert für die App (0071). Erneuert mit auswertung_schritt().

 SELECT gruppe,
    schluessel,
    h,
    datum,
    n_chargen,
    n_kohorten,
    lager_kg,
    verdunstet_kg,
    sockel_kg,
    faul_kg,
    kanal_kg,
    fax_kg,
    verkaufsfaehig_kg,
    gute_ware_kg,
    verlust_wasser_kg,
    verlust_faeulnis_kg,
    verlust_verkaufsfaehig_kg,
    verkaufsfaehig_anteil,
    verkaufsfaehig_unten_kg,
    verkaufsfaehig_oben_kg,
    verkaufsfaehig_je_tag_kg,
    verdunstet_je_tag_kg,
    faul_je_tag_kg,
    r_bekannt,
    f_bekannt,
    sockel_bekannt,
    kanal_bekannt,
    fax_bekannt,
    vollstaendig,
    modell_gilt,
    hochgerechnet,
    alter_tage,
    alter_von,
    alter_bis
   FROM v_prognose;
