-- gespeichert: erg_bilanz
-- v_saisonbilanz, gespeichert für die App Erneuert mit auswertung_schritt().

 SELECT heute,
    eingang_kg,
    n_chargen,
    ausgang_kg,
    verkauf_kg,
    marge_kg,
    entsorgt_kg,
    ausgang_fehler_kg,
    n_lieferungen,
    letzte_lieferung,
    vorlauf_kg,
    geliefert_kg,
    ausgelagert_kg,
    verlust_heute_kg,
    verlust_unten_kg,
    verlust_oben_kg,
    verdunstung_heute_kg,
    schimmel_heute_kg,
    sockel_heute_kg,
    fax_heute_kg,
    fax_erwartet_kg,
    kanal_ausgelagert_kg,
    kanal_unten_kg,
    kanal_oben_kg,
    im_haus_heute_kg,
    verkaufsfaehig_heute_kg,
    kanal_im_haus_kg,
    lager_kg,
    gegenprobe_wartet_kg,
    ueberzaehlung_kg,
    fax_durchsatz_kg,
    n_fax_arbeiten,
    verlust_bekannt,
    bilanz_rest_kg,
    bilanz_rest_anteil,
    ausgang_deckung,
    befund
   FROM v_saisonbilanz;
